# Generated by Django 3.0.8 on 2021-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время добавления'),
        ),
    ]
